DECLARE @name NVARCHAR(50) = 'Customer';

SELECT  ROUTINE_NAME
FROM    INFORMATION_SCHEMA.ROUTINES
WHERE   ROUTINE_DEFINITION LIKE '%' + @name + '%'
        AND ROUTINE_TYPE = 'PROCEDURE';

SELECT  CONSTRAINT_NAME
FROM    INFORMATION_SCHEMA.CHECK_CONSTRAINTS
WHERE   CONSTRAINT_NAME LIKE '%' + @name + '%';

SELECT  CONSTRAINT_NAME
FROM    INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
WHERE   CONSTRAINT_NAME LIKE '%' + @name + '%';

SELECT i.name, o.name
FROM sys.indexes i INNER JOIN sys.objects o ON o.object_id = i.object_id
WHERE i.name LIKE '%' + @name + '%';