version: "3.1"
services:
    db:
        image: mysql:latest
        network_mode: host
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: blog
            MYSQL_USER: wpadmin
            MYSQL_PASSWORD: cl3arSki3s
            MYSQL_ROOT_PASSWORD: cl3arSki3s
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        restart: always
    wp:
        depends_on:
            - db
        image: wordpress-xdebug-chromium
        network_mode: host
        ports:
            - 8080:80
        volumes:
            - .:/var/www/html
        restart: always
        environment:
            WORDPRESS_DB_NAME: blog
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wpadmin
            WORDPRESS_DB_PASSWORD: cl3arSki3s
            XDEBUG_CONFIG: remote_host=host.docker.internal remote_connect_back=1
volumes:
    persistent: