# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.synced_folder "./wordpress", "/vagrant"

  # Make Apache listen on port 8080 /etc/httpd/conf/httpd.conf
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.name = "centos-apache-php-mysql"
    vb.memory = "2048"
  end

  config.vm.provision "shell", path: "./installation/setup-apache-php-mysql.sh"
  config.vm.provision "shell", path: "./installation/installing-node-14-centos-7.sh"
  config.vm.provision "shell", path: "./installation/mysql-secure-installation.sh"
  config.vm.provision "shell", path: "./installation/wordpress-content-permissions.sh"

  ## Before running composer update in Tests folder
  ## Had to take ownership of files in test before using composer update
  # sudo chown -R $USER .

  ## When you vagrant ssh henceforth, you will login as root
  ## Adapted from https://stackoverflow.com/questions/25758737/vagrant-login-as-root-by-default
  #config.ssh.username = 'root'
  #config.ssh.password = 'vagrant'
  #config.ssh.insert_key = 'true'

end
