# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.synced_folder "./wordpress", "/vagrant"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.name = "centos-apache-php-mysql"
    vb.memory = "2048"
  end

  config.vm.provision "shell", path: "./installation/setup-apache-php-mysql.sh"
  config.vm.provision "shell", path: "./installation/installing-node-14-centos.sh"
  config.vm.provision "shell", path: "./installation/mysql-secure-installation.sh"
  config.vm.provision "shell", path: "./installation/wordpress-content-permissions.sh"

  ## Before running composer update in Tests folder
  # Had to take ownership of files in test before using composer update
  # sudo chown -R $USER .

end
