# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.synced_folder "./wordpress", "/vagrant", type: "rsync"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  #config.vm.provision "shell", path: "./installation/setup-apache-php-mysql.sh"
  #config.vm.provision "shell", path: "./installation/mysql-secure-installation.sh"
  ## WordPress script needed ... username: administrator password: Cl3arBlu3$ki3$
  # cp -r . /var/www/html

  ## Before running composer update in Tests folder
  # Had to take ownership of files in test before using composer update
  # sudo chown -R $USER .

end
