

	--/* Count Number Of Tables In A Database */
    SELECT  TABLE_NAME
    FROM    INFORMATION_SCHEMA.TABLES
    WHERE   TABLE_TYPE = 'BASE TABLE'
            AND TABLE_NAME <> 'sysdiagrams'
			AND TABLE_NAME NOT LIKE 'aspnet_%'

    SELECT  COUNT(*) AS ROUTINE_COUNT
    FROM    INFORMATION_SCHEMA.ROUTINES
    WHERE   ROUTINE_TYPE = 'PROCEDURE' --AND  ROUTINE_NAME LIKE 'table_%'

    --SELECT  TABLE_NAME
    --FROM    INFORMATION_SCHEMA.TABLES
    --WHERE   TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME <> 'sysdiagrams'
    --ORDER BY TABLE_NAME DESC
    --/* Count Number Of Views In A Database */
    --SELECT COUNT(*) AS VIEW_COUNT FROM INFORMATION_SCHEMA.VIEWS
    --/* Count Number Of Stored Procedures In A Database */
    --SELECT COUNT(*) AS PROCEDURE_COUNT FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'PROCEDURE'
    --/* Count Number Of Functions In A Database */
    --SELECT COUNT(*) AS FUNCTION_COUNT FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'FUNCTION'