
SELECT     DB_NAME() AS DATABASE_NAME, c.TABLE_SCHEMA, c.TABLE_NAME, c.COLUMN_NAME, c.ORDINAL_POSITION, c.COLUMN_DEFAULT, c.DATA_TYPE, 
                      c.CHARACTER_MAXIMUM_LENGTH, c.NUMERIC_PRECISION, c.NUMERIC_PRECISION_RADIX, c.NUMERIC_SCALE, c.DATETIME_PRECISION,
                      CASE WHEN z.COLUMN_NAME = c.COLUMN_NAME THEN c.COLUMN_NAME END AS PRIMARY_KEY
FROM INFORMATION_SCHEMA.COLUMNS AS c LEFT OUTER JOIN
(SELECT tc.[TABLE_SCHEMA], tc.[TABLE_NAME], ccu.[COLUMN_NAME]
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
        JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu ON tc.CONSTRAINT_NAME = ccu.Constraint_name
    WHERE tc.CONSTRAINT_TYPE = 'Primary Key') z ON c.[TABLE_NAME] = z.[TABLE_NAME] AND c.[TABLE_SCHEMA] = z.[TABLE_SCHEMA]

--SELECT tc.[TABLE_SCHEMA], tc.[TABLE_NAME], ccu.[COLUMN_NAME]
--    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
--        JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu ON tc.CONSTRAINT_NAME = ccu.Constraint_name
--    WHERE tc.CONSTRAINT_TYPE = 'Primary Key'

-- search thru all procedures
--SELECT DISTINCT o.name AS Object_Name,o.type_desc
--FROM sys.sql_modules m 
--INNER JOIN sys.objects o 
--ON m.object_id=o.object_id
--WHERE m.definition Like '%BXOLJMCCCHARG%'